;;;; wrappers-test.lisp --- the generated per-tool functions.
;;;;
;;;; SPDX-License-Identifier: MIT

(in-package #:nodecode.test)

(deftest mcp-cell-wrappers-fold-names ()
  (is (equal "read-file" (mcp::kebab "read_file")) "snake to kebab")
  (is (equal "search-issues" (mcp::kebab "searchIssues")) "camel to kebab")
  (is (equal "my-srv" (mcp::kebab "my_srv")) "server names too")
  (is (equal "get-html2-text" (mcp::kebab "getHTML2Text")) "runs of capitals stay together")
  (is (equal "a-b" (mcp::kebab "a.b")) "other characters become dashes")
  (is (equal "already-kebab" (mcp::kebab "already-kebab")) "kebab stays")
  (is (equal "MY-SRV/READ-FILE" (mcp::tool-function-name "my_srv" "read_file")))
  (let ((taken (make-hash-table :test #'equal)))
    (is (equal "S/READ-FILE" (mcp::unique-function-name "s" "read_file" taken)) "first come")
    (is (equal "S/READFILE" (mcp::unique-function-name "s" "readFile" taken)))
    (is (equal "S/READFILE-2" (mcp::unique-function-name "s" "readfile" taken)))))

(deftest mcp-cell-wrappers-define-real-functions (with-mcp-log-dir)
  (let* ((server (mcp::make-server :spec (mcp::make-server-spec :name "srv")))
         (seen nil))
    (setf (mcp::server-tools server)
          (list (list :name "read_file"
                      :description "Read one file."
                      :schema (cell-json "{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"per_page\":{\"type\":\"integer\"},\"t\":{}},\"required\":[\"path\"]}"))
                (list :name "gone_soon" :description "" :schema (nlk:make-json-object))))
    (mcp::sync-tool-functions server)
    (let ((symbol (find-symbol "SRV/READ-FILE" :nodecode-mcp)))
      (is (and symbol (fboundp symbol)) "the function exists")
      (is (eq :external (nth-value 1 (find-symbol "SRV/READ-FILE" :nodecode-mcp))))
      (is (eq symbol (getf (first (mcp::server-tools server)) :symbol)))
      (let* ((arglist (sb-introspect:function-lambda-list (fdefinition symbol)))
             (keys (loop for entry in arglist
                         when (consp entry) collect (first (first entry)))))
        (is (member :path keys) "the lambda list names the arguments")
        (is (member :per-page keys) "in kebab-case")
        (is (not (member :t keys)) "a property named t is left out")
        (is (member '&allow-other-keys arglist) "and other keys pass"))
      (let ((doc (documentation symbol 'function)))
        (is (search "Read one file." doc) "the description is the docstring")
        (is (search "(mcp:srv/read-file :path* :per-page :t)" doc) "with the call form")
        (is (search "required: path (string)" doc) "and the required arguments"))
      ;; The body is one APPLY of CALL: stub it to see the arguments arrive.
      (with-stubbed-fdefinition (mcp::call (server tool &rest args)
                                  (setf seen (list* server tool args))
                                  "ok")
        (is (equal "ok" (funcall symbol :path "/p" :per-page 2)) "the function calls CALL")
        (is (equal '("srv" "read_file" :path "/p" :per-page 2) seen))))
    (let ((gone (find-symbol "SRV/GONE-SOON" :nodecode-mcp)))
      (is (fboundp gone) "the second tool is a function too")
      (setf (mcp::server-tools server) (list (first (mcp::server-tools server))))
      (mcp::sync-tool-functions server)
      (is (not (fboundp gone)) "a tool gone from a fresh list is fmakunbound")
      (is (fboundp (find-symbol "SRV/READ-FILE" :nodecode-mcp)) "the survivor stays"))
    (mcp::undefine-tool-functions server)
    (is (not (fboundp (find-symbol "SRV/READ-FILE" :nodecode-mcp))))
    (is (null (mcp::server-symbols server)) "and forgets the symbols")))

(deftest mcp-cell-wrappers-of-a-dead-server-answer-offline ()
  (with-ready-mcp ("probe" (mcp-fixture-entry))
    (let ((symbol (find-symbol "PROBE/ECHO" :nodecode-mcp)))
      (handler-case (mcp:call "probe" "die") (mcp:mcp-offline () nil))
      (mcp::set-state (mcp-server "probe") :disabled)
      (is (signals-error mcp:mcp-offline (funcall symbol :message "x"))))))
