// zh.js -- the page's words in Simplified Chinese, keyed by their English as
// the page writes it (i18n.js). The object is JSON -- one "English": "中文"
// pair a line, sorted -- so the web cell's test reads it as the page does.
export const ZH = {
  "(no prompt)": "（无提示词）",
  "+{n} characters": "+{n} 个字符",
  ", ": "、",
  ", which a browser never sends to any server, so a tab opened any other way has nothing to show you.": " 之后，而浏览器从不把这一部分发给任何服务器，所以用其他方式打开的标签页没有内容可显示。",
  "1 · Name": "1 · 名称",
  "1, no retries": "1 次，未重试",
  "2 · Start from": "2 · 起始内容",
  "3 · Description (optional)": "3 · 描述（可选）",
  "30 days": "30 天",
  "4 · SOUL.md (optional)": "4 · SOUL.md（可选）",
  "5 · Review": "5 · 预览",
  "7 days": "7 天",
  "A backup is one file that holds this home whole: every session (a copy of the store taken while it runs), config.jsonc, SOUL.md, memory, skills and the cell folders.": "一份备份就是一个文件，完整保存这个主目录：每个会话（运行中拍下的存储副本）、config.jsonc、SOUL.md、记忆、技能和细胞文件夹。",
  "A bot answers a direct message from someone no allowlist names with a pairing code, and the ask waits here. Let in admits them by the name and id the platform shows; only the person who wrote holds the code, so when someone asks you to let them in, have them read you theirs and type it below.": "不在任何允许名单上的人私信机器人时，机器人会回复一个配对码，这条请求就在这里等待。「放行」按平台显示的名字和 ID 接纳对方；配对码只在写信的人手里，所以有人请你放行时，让对方把配对码念给你，再填到下面。",
  "A browser asks from the address, shows a code, and waits two minutes; allowing it here or with /link allow in a shell lets it in for good, until it is removed.": "浏览器从该地址发起请求，显示一个代码并等待两分钟；在这里允许，或在终端中运行 /link allow，就能让它长期访问，直到被移除。",
  "A browser is asking": "有浏览器请求访问",
  "A code nobody lets in lapses an hour after the bot gave it; there is no refusing one here. The person may ask for a new code ten minutes after their last, and three can wait at once: past that, a stranger is told you have too many waiting.": "无人放行的配对码在机器人发出一小时后失效；这里没有拒绝操作。对方要在上次请求十分钟后才能再要新码，同时最多三条请求等待：超过后，陌生人会被告知等待的人太多。",
  "A code someone gave you": "别人给你的配对码",
  "A command runs on this machine as a child process over stdio; a URL is reached over streamable HTTP. Test tries it on a connection of its own and closes it; nothing is saved until Add server. A key is written into mcp.servers in config.jsonc, where the cell reads it. A server works with this organism's own reach: add one you trust.": "命令在本机作为子进程运行，通过 stdio 通信；URL 通过 streamable HTTP 访问。「测试」会单独建立一个连接试用，随后关闭；点「添加服务器」之前什么都不会保存。密钥会写入 config.jsonc 的 mcp.servers，细胞从那里读取。服务器拥有与此实例相同的权限：只添加你信任的服务器。",
  "A command runs on this machine as a child process over stdio; a URL is reached over streamable HTTP. Test tries it on a connection of its own and closes it; nothing is saved until Add server. A server works with this organism's own reach: add one you trust.": "命令在本机作为子进程运行，通过 stdio 通信；URL 通过 streamable HTTP 访问。「测试」会单独建立一个连接试用，随后关闭；点「添加服务器」之前什么都不会保存。服务器拥有与此实例相同的权限：只添加你信任的服务器。",
  "A folder, such as ~/code/webshop": "文件夹，例如 ~/code/webshop",
  "A fork": "分叉",
  "A hub cell is someone else's code. It runs inside this organism with full authority, your files, keys and sessions included, and is pinned to the commit shown: read the code at that commit before you turn it on.": "细胞中心的细胞是别人写的代码。它在此实例内以完全权限运行，能访问你的文件、密钥和会话，并固定在所示的提交上：开启之前，请先读一读该提交下的代码。",
  "A job runs in a session of its own, cron-<id>: open its name to read what it did.": "每个任务在自己的会话 cron-<id> 中运行：点它的名字即可查看它做了什么。",
  "A key or the default model is used from the next turn on; nothing restarts. A cell reads its section of config.jsonc when it starts: after changing that section, restart the cell under Cells.": "密钥和默认模型从下一轮起生效，无需重启。细胞在启动时读取它在 config.jsonc 中的配置段：改动该段后，请在「细胞」下重启这个细胞。",
  "A link that leads nowhere": "指向不存在位置的链接",
  "A link that leads outside the folder": "指向文件夹之外的链接",
  "A link to a place inside the folder": "指向文件夹内某处的链接",
  "A pick here changes this session and becomes the default for new sessions. Sessions already begun keep their own model.": "这里的选择会改变此会话，并成为新会话的默认模型。已开始的会话保留各自的模型。",
  "A pick here goes to the session your first message opens and becomes the default for new sessions.": "这里的选择用于你第一条消息打开的会话，并成为新会话的默认模型。",
  "A profile is a home of its own: its config, keys, store, layer and gateway, so each one runs as an organism of its own. This page belongs to the gateway of {name} and stays there; another profile's page opens from a terminal with the command under its row.": "每个配置档都是一个独立的主目录：有自己的配置、密钥、存储、代码层和网关，因此各自作为独立的实例运行。本页面属于 {name} 的网关，不会切换到别处；其他配置档的页面，用它那一行下方的命令在终端中打开。",
  "A profile named {name} already exists.": "名为 {name} 的配置档已存在。",
  "A release that can go live does so at once, in this organism and every attached shell; one that changes what it boots with runs from the next restart.": "能直接上线的版本会立即生效，包括此实例和每个已连接的终端；改动了启动内容的版本从下次重启起运行。",
  "A restart: {what}.": "重启：{what}。",
  "A session has no {view} view on this page, so this is its chat.": "此页面上的会话没有 {view} 视图，所以这里显示它的对话。",
  "Add": "添加",
  "Add a job": "添加任务",
  "Add a server": "添加服务器",
  "Add it": "添加",
  "Add job": "添加任务",
  "Add key": "添加密钥",
  "Add server": "添加服务器",
  "Cells": "细胞",
  "Added": "已添加",
  "Adding it up…": "正在统计…",
  "Adding…": "正在添加…",
  "Address": "地址",
  "All": "全部",
  "All settings": "全部设置",
  "All sources": "全部来源",
  "All told": "迄今",
  "Allow": "允许",
  "Allowed browsers": "已允许的浏览器",
  "Allowing…": "正在允许…",
  "Among them: {names}, and {n} more.": "其中有：{names}，另有 {n} 个。",
  "Among them: {names}.": "其中有：{names}。",
  "A cell is a folder in the cell folder. On puts it there, with the cells it needs, and loads it into this organism now; off takes it out and stops it. Code already loaded stays in this organism until a restart.": "细胞就是细胞文件夹中的一个文件夹。开启会把它连同它依赖的细胞放进去，并立即加载到此实例；关闭会把它移出并停止它。已加载的代码在重启之前仍留在此实例中。",
  "A cell is a folder in {folder}. On puts it there, with the cells it needs, and loads it into this organism now; off takes it out and stops it. Code already loaded stays in this organism until a restart.": "细胞就是 {folder} 中的一个文件夹。开启会把它连同它依赖的细胞放进去，并立即加载到此实例；关闭会把它移出并停止它。已加载的代码在重启之前仍留在此实例中。",
  "An empty home: the setup walk runs at its first launch.": "空的主目录：首次启动时运行设置向导。",
  "And {n} more, not listed.": "另有 {n} 项未列出。",
  "Another provider": "其他提供商",
  "Answer and step requests": "回答与步骤请求",
  "Arguments, split at spaces": "参数（以空格分隔）",
  "As the profile": "恢复为配置档",
  "Asking to be let in": "请求放行",
  "Asking…": "询问中…",
  "Attempts that failed": "失败的尝试",
  "Auto": "自动",
  "Back up now": "立即备份",
  "Backed up: {text}": "已备份：{text}",
  "Background gateway": "后台网关",
  "Backing up: {step}… {seconds} s": "备份中：{step}… {seconds} s",
  "Backing up…": "备份中…",
  "Backups": "备份",
  "Bring sessions back from a file Export saved (.jsonl)": "从「导出」保存的文件（.jsonl）恢复会话",
  "Busiest sessions": "最忙的会话",
  "Busiest: {day} around {hour}, {turns} in that hour.": "最忙：{day} {hour} 前后，该小时 {turns}。",
  "By folder": "按文件夹",
  "Cache miss": "缓存未命中",
  "Call {n} re-read the prompt at full price and waited {wait} for its first word.": "第 {n} 次调用按全价重读了提示词，等了 {wait} 才出首字。",
  "Call {n} re-read the prompt at full price.": "第 {n} 次调用按全价重读了提示词。",
  "Call {n} waited {wait} for its first word.": "第 {n} 次调用等了 {wait} 才出首字。",
  "Call {n} · {model} · waited {wait} · wrote {write} · {cost}": "第 {n} 次调用 · {model} · 等待 {wait} · 输出 {write} · {cost}",
  "Calls": "调用",
  "Cancel": "取消",
  "Cannot be turned on here: it needs {needs}, which this build does not have.": "无法在此开启：它需要 {needs}，而此构建没有。",
  "Catalog": "目录",
  "Change the default in Control": "在控制台更改默认模型",
  "Changed": "修改时间",
  "Changed at": "变化位置",
  "Change…": "更改…",
  "Channels": "频道",
  "Chat": "对话",
  "Check": "检查",
  "Check everything": "全面检查",
  "Check for an update": "检查更新",
  "Checking…": "检查中…",
  "Checkpoint forks": "检查点分叉",
  "Choose a model": "选择模型",
  "Clear the form": "清空表单",
  "Close": "关闭",
  "Close SOUL": "关闭 SOUL",
  "Close the form": "关闭表单",
  "Command, or a URL": "命令或 URL",
  "Commands": "命令",
  "Compared with": "对比对象",
  "Complete, on its defaults.": "已就绪，使用默认值。",
  "Complete.": "已就绪。",
  "Connected": "已连接",
  "Connected again": "已重新连接",
  "Connected in {connect} and listed {tools} in {list}.": "连接用时 {connect}，列出 {tools}用时 {list}。",
  "Connected in {connect} and listed {tools} in {list}: {server}.": "连接用时 {connect}，列出 {tools}用时 {list}：{server}。",
  "Connecting": "正在连接",
  "Connecting.": "正在连接。",
  "Connection dropped or timed out": "连接中断或超时",
  "Context": "上下文",
  "Control": "控制",
  "Control has no {tab} tab, so it opens on {label}.": "控制面板没有 {tab} 标签页，所以停留在「{label}」。",
  "Conversation only": "仅对话",
  "Copied": "已复制",
  "Copied the address": "已复制地址",
  "Copied what was sent": "已复制发送的内容",
  "Copied: {text}": "已复制：{text}",
  "Copy": "复制",
  "Cost": "费用",
  "Costliest sessions": "花费最多的会话",
  "Could not check: {error}": "无法检查：{error}",
  "Could not copy; select it by hand: {text}": "无法复制，请手动选取：{text}",
  "Could not open {name}: {error}": "无法打开 {name}：{error}",
  "Could not read health: {error}": "无法读取健康状态：{error}",
  "Could not read it: {error}": "无法读取：{error}",
  "Could not read the MCP servers: {error}": "无法读取 MCP 服务器：{error}",
  "Could not read the cells: {error}": "无法读取细胞：{error}",
  "Could not read the channels: {error}": "无法读取频道：{error}",
  "Could not read the gateway: {error}": "无法读取网关：{error}",
  "Could not read the index: {error}": "无法读取索引：{error}",
  "Could not read the jobs: {error}": "无法读取定时任务：{error}",
  "Could not read the link: {error}": "无法读取远程访问：{error}",
  "Could not read the profiles: {error}": "无法读取配置档：{error}",
  "Could not read the sessions.": "无法读取会话列表。",
  "Could not read this session: {error}": "无法读取此会话：{error}",
  "Could not read usage: {error}": "无法读取用量：{error}",
  "Couldn't ask the gateway: {why}": "无法询问网关：{why}",
  "Couldn't copy: the browser refused the clipboard": "无法复制：浏览器拒绝访问剪贴板",
  "Couldn't count what would go: {why}": "无法统计会删除哪些内容：{why}",
  "Couldn't download {name}: {why}": "无法下载 {name}：{why}",
  "Couldn't drop turns from the context: {why}": "无法从上下文移出轮次：{why}",
  "Couldn't export: {why}": "无法导出：{why}",
  "Couldn't fork the session: {why}": "无法分叉会话：{why}",
  "Couldn't import {file}: {why}": "无法导入 {file}：{why}",
  "Couldn't open the session on your pick: {why}": "无法按你的选择打开会话：{why}",
  "Couldn't prune: {why}": "无法清理：{why}",
  "Couldn't rename the session: {why}": "无法重命名会话：{why}",
  "Couldn't save the Markdown: {why}": "无法保存 Markdown：{why}",
  "Couldn't set reasoning to {value}: {why}": "无法把推理设为 {value}：{why}",
  "Couldn't start a session: {why}": "无法开启会话：{why}",
  "Couldn't switch to {model}: {why}": "无法切换到 {model}：{why}",
  "Couldn't upload {name}: {why}": "无法上传 {name}：{why}",
  "Counting what would go…": "正在统计会删除哪些内容…",
  "Create": "创建",
  "Create makes {name} at {path}: {start}; {soul}. A store and a layer of its own; this page stays on {here}.": "「创建」会在 {path} 建立 {name}：{start}；{soul}。它有自己的存储和代码层；本页面仍留在 {here}。",
  "Create makes {name} at {path}: {start}; {soul}; described as \"{description}\". A store and a layer of its own; this page stays on {here}.": "「创建」会在 {path} 建立 {name}：{start}；{soul}；描述为「{description}」。它有自己的存储和代码层；本页面仍留在 {here}。",
  "Creating…": "正在创建…",
  "Ctrl+scroll or pinch to zoom · drag to move · double-click a bar": "Ctrl+滚轮或双指缩放 · 拖动平移 · 双击色条聚焦",
  "Dark": "深色",
  "Dashboard": "仪表盘",
  "Default": "默认",
  "Default (the model's own)": "默认（模型自己的）",
  "Default ({model})": "默认（{model}）",
  "Default ({value})": "默认（{value}）",
  "Default model": "默认模型",
  "Delete": "删除",
  "Delete the backup made {when}? The file is gone for good; this home is untouched.": "删除 {when} 的备份？文件将永久删除；此主目录不受影响。",
  "Delete the job {id}? It fires no more; its session keeps what it did.": "删除任务 {id}？它将不再触发；它的会话会保留它做过的一切。",
  "Delete the sessions no one has touched in a while": "删除一段时间内无人使用的会话",
  "Delete the ticked sessions, and every session under them": "删除勾选的会话，以及其下的所有会话",
  "Delete {name}? Its whole home goes for good: its store with every session, its layer, its config, and whatever memory and keys it holds of its own.": "删除 {name}？它的整个主目录将永久删除：存有全部会话的存储、代码层、配置，以及它自己持有的记忆和密钥。",
  "Delete {name}? Its whole home goes for good: its store with every session, its layer, its config, and whatever memory and keys it holds of its own. What it shares by link ({shares}) stays with {source}.": "删除 {name}？它的整个主目录将永久删除：存有全部会话的存储、代码层、配置，以及它自己持有的记忆和密钥。通过链接共享的内容（{shares}）仍保留在 {source}。",
  "Delete {n} session and the {m} session under it?": "删除 {n} 个会话及其下的 {m} 个会话？",
  "Delete {n} session and the {m} sessions under it?": "删除 {n} 个会话及其下的 {m} 个会话？",
  "Delete {n} session?": "删除 {n} 个会话？",
  "Delete {n} sessions and the {m} session under them?": "删除 {n} 个会话及其下的 {m} 个会话？",
  "Delete {n} sessions and the {m} sessions under them?": "删除 {n} 个会话及其下的 {m} 个会话？",
  "Delete {n} sessions?": "删除 {n} 个会话？",
  "Deleted {n} session": "已删除 {n} 个会话",
  "Deleted {n} session; kept {kept}": "已删除 {n} 个会话；保留了 {kept}",
  "Deleted {n} session; {m} stayed": "已删除 {n} 个会话；{m} 个保留",
  "Deleted {n} sessions": "已删除 {n} 个会话",
  "Deleted {n} sessions; kept {kept}": "已删除 {n} 个会话；保留了 {kept}",
  "Deleted {n} sessions; {m} stayed": "已删除 {n} 个会话；{m} 个保留",
  "Deleting…": "正在删除…",
  "Deny": "拒绝",
  "Done": "完成",
  "Done, and this page, which came through the link, is cut off with it.": "已完成。本页面经由远程访问打开，也随之断开了。",
  "Download": "下载",
  "Drop the oldest half of this session's context?": "移出此会话上下文中较早的一半？",
  "Drop to upload into {folder}": "松开即上传到 {folder}",
  "Dropped {n} turn from the context": "已从上下文移出 {n} 轮",
  "Dropped {n} turns from the context": "已从上下文移出 {n} 轮",
  "Edit": "编辑",
  "Ended because": "结束原因",
  "Errors": "错误",
  "Every hub cell this platform runs is on.": "此平台能运行的细胞中心细胞都已开启。",
  "Every part of config.jsonc that something here declares: open one to change it. A secret is never shown here; paste a new one to replace it.": "config.jsonc 中由这里的组件声明的每个配置段：打开一个即可修改。机密从不在这里显示；粘贴一个新的即可替换。",
  "Every session shown": "所有显示的会话",
  "Every source, in every folder.": "所有来源，所有文件夹。",
  "Everything a clone of its settings copies, your own cell folders and the layer with its git history too, and memory, skills, secrets and auth.json copied rather than shared. Never the store.": "复制设置时复制的一切，再加上你自己的细胞文件夹和带 git 历史的代码层；记忆、技能、机密信息和 auth.json 是复制而不是共享。存储从不复制。",
  "Everything · API-equivalent prices": "全部时间 · 按 API 等价价格计",
  "Evict": "移出",
  "Export": "导出",
  "Failed": "失败",
  "Failed attempts over attempts. An attempt failed when the provider's error was retried, when the turn moved to another model, or when the error ended the turn; every other attempt is a model call that answered.": "失败尝试占全部尝试的比例。提供商出错后重试、本轮换用其他模型、或错误让本轮结束，都算一次失败的尝试；其余每次尝试都是一次得到回答的模型调用。",
  "Failed turns over the turns that ended in the folder; a turn someone stopped ended, it did not fail.": "失败轮次占此文件夹内已结束轮次的比例；被人停止的轮次算作结束，不算失败。",
  "Failing.": "连接失败。",
  "Fewer settings": "收起设置",
  "Files": "文件",
  "Filter": "筛选",
  "Filter lines": "筛选行",
  "Filter sessions": "筛选会话",
  "Filter the log": "筛选日志",
  "Filter what is kept": "筛选保存的内容",
  "Find a model": "查找模型",
  "First word": "首字",
  "First word after": "首字耗时",
  "First word, typical": "首字耗时（典型）",
  "Fit": "全览",
  "Flagged": "已标记",
  "Folder": "文件夹",
  "Folder for the new session": "新会话的文件夹",
  "Folder:": "文件夹：",
  "Follow": "跟随",
  "Follow the browser's languages": "跟随浏览器的语言",
  "Follow the system's light or dark setting": "跟随系统的浅色或深色设置",
  "Forget": "忘记",
  "Forget {name}? Its file leaves its cell in one commit, which git keeps; the agent no longer lists or finds it.": "忘记 {name}？它的文件会通过一次提交离开所在的细胞，git 会保留这次提交；智能体不再列出或找到它。",
  "Fork": "分叉",
  "Fri": "周五",
  "From": "来源",
  "From cache": "缓存命中",
  "From cache under half is marked. Went wrong is the share of attempts that failed; hover it for the statuses. First word is the typical wait (TTFT p50); speed is output tokens over the time spent writing them.": "「缓存命中」低于一半的会被标出。「出错」是失败尝试所占的比例，悬停可看各状态码。「首字」是典型等待时间（TTFT p50）；「速度」是输出 Token 数除以输出所用的时间。",
  "From the hub": "来自细胞中心",
  "Full price": "全价",
  "Gateway": "网关",
  "Go there": "前往",
  "Go to turn {n} on its branch?": "前往分支上的第 {n} 轮？",
  "Go to turn {n}?": "前往第 {n} 轮？",
  "Goes with the session it hangs under": "随其上级会话一起处理",
  "Health check": "健康检查",
  "History": "历史",
  "Home": "主目录",
  "How it runs": "运行方式",
  "How the agent sounds in a channel: its voice, its stance, its boundaries.": "智能体在频道中的说话方式：语气、立场和边界。",
  "How the agent sounds in this profile's channels.": "智能体在这个配置档的频道中的说话方式。",
  "How the agent sounds in this profile's channels. Empty keeps the SOUL.md the clone carries.": "智能体在这个配置档的频道中的说话方式。留空则保留克隆带来的 SOUL.md。",
  "Image": "图片",
  "Import": "导入",
  "Imported {n} session": "已导入 {n} 个会话",
  "Imported {n} session; {k} session it builds on was here already": "已导入 {n} 个会话；其依赖的 {k} 个会话已经存在",
  "Imported {n} session; {k} sessions it builds on were here already": "已导入 {n} 个会话；其依赖的 {k} 个会话已经存在",
  "Imported {n} sessions": "已导入 {n} 个会话",
  "Imported {n} sessions; {k} session it builds on was here already": "已导入 {n} 个会话；其依赖的 {k} 个会话已经存在",
  "Imported {n} sessions; {k} sessions it builds on were here already": "已导入 {n} 个会话；其依赖的 {k} 个会话已经存在",
  "In conversations": "对话中的匹配",
  "In process": "进程内",
  "In the folder, not loaded in this organism yet.": "已在文件夹中，尚未加载到此实例。",
  "In the folder; it loads at the next restart.": "已在文件夹中；下次重启时加载。",
  "In this range": "此范围内",
  "Index": "索引",
  "Install": "安装",
  "Install {name} from the hub? It is someone else's code, and it runs inside this organism with full access to your files, keys and sessions. It is pinned to {pin}: read the code at that commit before you say yes.": "从细胞中心安装 {name}？这是别人写的代码，它会在此实例内运行，能完全访问你的文件、密钥和会话。它固定在 {pin}：同意之前，请先读一读该提交下的代码。",
  "It already ran": "它已经运行了",
  "It asked to run steps": "它请求执行步骤",
  "It comes back as a profile: a home of its own beside this one, which nothing here changes. nodecode -p NAME opens it; nodecode profile use NAME makes it the one a bare launch opens. It answers the same channels this home does, so run one of the two at a time.": "它会恢复为一个配置档：与当前主目录并列的独立主目录，这里的任何操作都不会改动它。nodecode -p NAME 打开它；nodecode profile use NAME 让直接启动时打开它。它和当前主目录接入同样的频道，所以两者一次只运行一个。",
  "It did not answer: {error}": "它没有响应：{error}",
  "It finished its answer": "它完成了回答",
  "It hit the output limit": "它达到了输出上限",
  "It holds your provider keys and pasted secrets too: keep the file where you keep passwords.": "它也包含你的提供商密钥和粘贴过的机密：请像保管密码一样保管这个文件。",
  "It is kept as a define-memory in your knowledge cell under the home, one file and one commit.": "它会作为一个 define-memory 保存在主目录下你的知识细胞中：一个文件，一次提交。",
  "It is on, and the relay cannot be reached; this machine keeps trying.": "已开启，但无法连上中继；本机会继续尝试。",
  "It is on, and the relay has not answered yet; this machine keeps trying.": "已开启，但中继尚未响应；本机会继续尝试。",
  "It moved to another model {n} time.": "换用其他模型 {n} 次。",
  "It moved to another model {n} times.": "换用其他模型 {n} 次。",
  "Its key": "它的密钥",
  "Its own page, from a terminal, once it runs ({command}):": "它自己的页面，待它运行后（{command}）在终端中打开：",
  "Its own page, from a terminal:": "它自己的页面，在终端中打开：",
  "Its settings": "它的设置",
  "Jump to the latest": "跳到最新",
  "Keep it": "保留",
  "Keeping…": "保存中…",
  "Kept in {folder}, readable by you alone.": "保存在 {folder}，只有你能读取。",
  "Kept in {to}, readable by you alone (mode 0600); {file} names the file, so config.jsonc never holds the {noun} itself.": "保存在 {to}，只有你能读取（权限 0600）；{file} 指向该文件，所以 config.jsonc 里从不存放 {noun} 本身。",
  "Kept the {name} already there": "已保留原有的 {name}",
  "Key for {provider}": "{provider} 的密钥",
  "Language": "语言",
  "Last error: {error}": "最近一次错误：{error}",
  "Last refused: {what}": "上次拒绝：{what}",
  "Last run {when}: {status}": "上次运行 {when}：{status}",
  "Last run {when}: {status}, {line}": "上次运行 {when}：{status}，{line}",
  "Last turn {time}": "上一轮 {time}",
  "Latest failed turns": "最近失败的轮次",
  "Latest model calls": "最近的模型调用",
  "Let in": "放行",
  "Letters, digits, _ and -": "字母、数字、_ 和 -",
  "Letting in…": "正在放行…",
  "Level": "级别",
  "Light": "浅色",
  "Link": "远程访问",
  "List the sessions of every folder": "列出所有文件夹的会话",
  "Listed {tools} in {list} on the connection the agent uses, which connected in {connect}.": "在智能体所用的连接上列出 {tools}用时 {list}，该连接建立用时 {connect}。",
  "Listed {tools} in {list} on the connection the agent uses.": "在智能体所用的连接上列出 {tools}用时 {list}。",
  "Load now": "立即加载",
  "Logs": "日志",
  "Looking…": "正在加载…",
  "MCP servers": "MCP 服务器",
  "Make default": "设为默认",
  "Make default writes the profile a bare nodecode runs from the next launch on; nothing running moves. Export saves a home as an archive without its store, secrets and credentials, which nodecode profile import brings back. Named profiles live in {folder}.": "「设为默认」会记下直接运行 nodecode 时使用的配置档，从下次启动起生效；正在运行的不受影响。「导出」把主目录存为归档，不含存储、机密信息和凭据，可用 nodecode profile import 导回。命名配置档位于 {folder}。",
  "Making default…": "正在设为默认…",
  "Memory at peak": "上下文峰值",
  "Memory sent": "发送的上下文",
  "Memory trimmed": "上下文已裁剪",
  "Message this session": "给此会话发消息",
  "Message {n}": "第 {n} 条消息",
  "Message {n} of {total}": "第 {n} 条消息（共 {total} 条）",
  "Messages": "消息",
  "Model": "模型",
  "Model and reasoning": "模型和推理",
  "Model call {n}: waited {wait}, wrote for {write}": "第 {n} 次模型调用：等待 {wait}，输出 {write}",
  "Model calls": "模型调用",
  "Model calls by day": "每日模型调用",
  "Model writing": "模型输出",
  "Models": "模型",
  "Mon": "周一",
  "Moved from {from} to {to} ({reason}).": "从 {from} 换到了 {to}（{reason}）。",
  "Moved {from} → {to} ({reason}) ×{n}": "换用 {from} → {to}（{reason}）×{n}",
  "Name": "名称",
  "Name (optional)": "名称（可选）",
  "Name it, and this line says what Create makes.": "填写名称后，这里会说明「创建」将建立什么。",
  "Needs {needs} on this machine.": "需要本机装有 {needs}。",
  "Never run. It will ask: {prompt}": "还没运行过。运行时会发送：{prompt}",
  "New memory": "新建记忆",
  "New or changed": "新增或变化",
  "New profile": "新建配置档",
  "New session": "新会话",
  "New sessions, and sessions that follow the default, use it; a session given its own model keeps it.": "新会话和跟随默认设置的会话都会使用它；单独指定了模型的会话保持不变。",
  "Next call": "下一次调用",
  "No SOUL.md yet; Save writes {file}": "还没有 SOUL.md；「保存」会写入 {file}",
  "No backup yet.": "还没有备份。",
  "No browser is allowed yet. Open the address in a browser, and allow it here when it asks.": "还没有允许任何浏览器。在浏览器中打开该地址，它请求时在这里允许即可。",
  "No browser is allowed yet. Scan the code with a phone, or open the address in any browser, and allow it here when it asks.": "还没有允许任何浏览器。用手机扫描二维码，或在任意浏览器中打开该地址，它请求时在这里允许即可。",
  "No browser is allowed. Turn the link on, open its address in a browser, and allow it here when it asks.": "没有允许任何浏览器。开启远程访问，在浏览器中打开其地址，它请求时在这里允许即可。",
  "No channel is installed. Add one, then Set up walks it here.": "还没有安装频道。添加一个后，点「设置」在这里一步步配置。",
  "No channel is running, so nobody can ask to be let in. A running bot answers a direct message from someone no allowlist names with a pairing code, and the ask waits here.": "没有频道在运行，所以没有人能请求放行。运行中的机器人收到不在任何允许名单上的人的私信时，会回复一个配对码，这条请求就在这里等待。",
  "No description.": "无描述。",
  "No files to restore.": "没有需要恢复的文件。",
  "No job is scheduled.": "没有定时任务。",
  "No line matches.": "没有匹配的行。",
  "No model calls in this range.": "此范围内没有模型调用。",
  "No price is known for these {calls}, so they are counted instead, each split evenly over the steps it asked for; a call that asked for none was writing the reply.": "这 {calls}都没有已知价格，所以改为计数：每次调用平均分摊到它请求的步骤上；没有请求步骤的调用是在撰写回复。",
  "No price is known for this model, so cost shows as a dash.": "此模型没有已知价格，所以费用显示为短横。",
  "No price is known for this model, so its cost is unknown.": "此模型没有已知价格，所以费用未知。",
  "No price is known for {model}, so cost shows as a dash.": "{model} 没有已知价格，所以费用显示为短横。",
  "No provider is named yet.": "还没有指定任何提供商。",
  "No server is set. Add one below, or pick one from the catalog.": "还没有设置服务器。在下方添加一个，或从目录中选一个。",
  "No session matches.": "没有匹配的会话。",
  "No sessions in {folder} yet.": "{folder} 中还没有会话。",
  "No turns in this range.": "此范围内没有轮次。",
  "No turns yet.": "还没有轮次。",
  "Nobody is asking.": "没有人在请求。",
  "Nobody is let in by pairing yet.": "还没有人通过配对被放行。",
  "None": "无",
  "None of these can be deleted now.": "这些会话现在都不能删除。",
  "None returned an error.": "没有步骤返回错误。",
  "Not connected to the gateway": "未连接到网关",
  "Not connected yet": "尚未连接",
  "Not copied": "未复制",
  "Not deleted: {why}.": "未删除：{why}。",
  "Not done: {error}": "未完成：{error}",
  "Not opened: {why}": "未打开：{why}",
  "Not recorded": "未记录",
  "Not set": "未设置",
  "Not shown: this file is not text or a picture. Download saves it.": "未显示：此文件不是文本或图片。可下载保存。",
  "Not shown: this file is too large to read here. Download saves it.": "未显示：此文件太大，无法在这里查看。可下载保存。",
  "Not touched in": "闲置超过",
  "Nothing": "空白",
  "Nothing changed.": "没有改动。",
  "Nothing has run in this session yet.": "此会话还没有运行过任何内容。",
  "Nothing here yet.": "这里还没有会话。",
  "Nothing in this folder yet. Upload, or drop files here, to put some in it.": "此文件夹还是空的。上传文件，或把文件拖到这里即可放入。",
  "Nothing in this range.": "此范围内没有内容。",
  "Nothing kept matches.": "没有匹配的保存内容。",
  "Nothing kept yet. The agent keeps a memory or a skill when one is worth keeping; New memory keeps one here.": "还没有保存任何内容。值得保存时，智能体会保存一条记忆或一个技能；「新建记忆」可在这里保存一条。",
  "Nothing matches in {folder}.": "{folder} 中没有匹配项。",
  "Nothing matches.": "没有匹配项。",
  "Nothing ran in this range.": "此范围内没有运行任何内容。",
  "Nothing reaches this machine through the relay.": "没有任何访问能经中继到达本机。",
  "Nothing to look at": "没有需要查看的问题",
  "Nothing to pick from yet.": "暂时没有可选项。",
  "Nothing went wrong in this range.": "此范围内一切正常。",
  "Nothing written yet.": "还没有写入任何内容。",
  "Off": "关",
  "Off.": "已关闭。",
  "Off. Its code stays loaded in this organism until a restart.": "已关闭。它的代码在重启之前仍加载在此实例中。",
  "Older turns were set aside to make room. They stay in the transcript.": "较早的轮次已移出上下文以腾出空间，它们仍保留在对话记录中。",
  "On": "开",
  "On.": "已开启。",
  "One declarative sentence": "一句陈述句",
  "One line this machine dials out to the relay at {relay}: nothing listens here, and the sessions, the store and the turns stay on this machine. On, the link keeps the gateway running while no shell is open.": "本机主动向 {relay} 的中继拨出一条连接：本机不监听任何端口，会话、存储和每一轮对话都留在本机。开启时，即使没有打开终端，远程访问也会让网关保持运行。",
  "One model call": "一次模型调用",
  "One thing is worth a look below.": "下面有 1 处值得一看。",
  "Only sessions nothing was said in": "仅限没有任何消息的会话",
  "Open Logs": "打开日志",
  "Open Settings": "打开设置",
  "Open a session": "开启会话",
  "Open call {n}": "打开第 {n} 次调用",
  "Open its settings": "打开它的设置",
  "Open one to see its turn on the Run view, where the inspector says why a call was slow or paid full price.": "打开一项，在运行视图中查看它所在的轮次；检查器会说明调用为何慢、为何按全价计费。",
  "Open the file": "打开文件",
  "Open {name}": "打开 {name}",
  "Or pick one up in {folder}": "或继续 {folder} 中的会话",
  "Other tools: {tools}": "其他工具：{tools}",
  "Paid full price for the prompt": "提示词按全价计费",
  "Paid full price for {tokens} tokens: the prompt changed at message {message}.": "{tokens} Token 按全价计费：提示词在第 {message} 条消息处发生了变化。",
  "Paid full price for {tokens} tokens: the provider did not reuse the prompt.": "{tokens} Token 按全价计费：提供商没有复用提示词。",
  "Pairing": "配对",
  "Paste the {noun}": "粘贴 {noun}",
  "Pause": "暂停",
  "Pick by name": "按名称选择",
  "Point a phone's camera at the code to open the address there. The phone asks to open this machine; allow its code here, or with /link allow in a shell.": "用手机相机扫描二维码，即可在手机上打开该地址。手机会请求访问本机；在这里允许它的代码，或在终端中运行 /link allow。",
  "Previous call": "上一次调用",
  "Problems": "问题",
  "Process": "进程",
  "Profiles": "配置档",
  "Prompt changed at": "提示词变化位置",
  "Provider error": "提供商错误",
  "Provider failure": "提供商故障",
  "Provider keys": "提供商密钥",
  "Provider overloaded": "提供商过载",
  "Prune": "清理",
  "Put files from this computer into the folder on screen; or drop them on the list": "把这台电脑上的文件放进当前显示的文件夹；也可以直接拖到列表上",
  "Range": "范围",
  "Rate limited": "被限流",
  "Raw": "原始",
  "Read again": "重新读取",
  "Read what is written as it is written": "实时读取新写入的内容",
  "Read when the organism starts.": "实例启动时读取。",
  "Reading the catalog…": "正在读取目录…",
  "Reading the files it would restore…": "正在读取会恢复的文件…",
  "Reading the hub's index…": "正在读取细胞中心的索引…",
  "Reading the tree…": "正在读取会话树…",
  "Reading this session…": "正在读取此会话…",
  "Reading what was sent…": "正在读取发送内容…",
  "Reading…": "正在读取…",
  "Reads the store back whole, then checks the build on disk, the free disk, config.jsonc and every section declared in it, the default provider's key and a release waiting: what /doctor prints in a shell.": "完整读回存储，再检查磁盘上的构建、剩余磁盘空间、config.jsonc 及其中声明的每个配置段、默认提供商的密钥，以及有没有待安装的版本：与 /doctor 在终端中打印的内容相同。",
  "Reasoning": "推理",
  "Recent folders": "最近的文件夹",
  "Reconnect now": "立即重连",
  "Redo": "重做",
  "Reflections": "反思",
  "Refused": "被拒绝",
  "Refused at start: {why}": "启动时被拒绝：{why}",
  "Refused by its entry in config.jsonc": "被 config.jsonc 中的配置项拒绝",
  "Reload": "重新加载",
  "Remove": "移除",
  "Remove the key saved for {provider}? A turn on {provider} has none after, unless the environment gives one.": "移除为 {provider} 保存的密钥？之后在 {provider} 上的轮次将没有密钥可用，除非环境变量提供一个。",
  "Remove this browser? This page came through it, so it is cut off now, and coming back takes allowing it again at the machine.": "移除这个浏览器？本页面正是经由它打开的，会立即断开；要重新访问，需要在本机上再次允许。",
  "Remove this image": "移除这张图片",
  "Remove {agent}? It can no longer open this machine, and a page it has open is cut off now.": "移除 {agent}？它将无法再访问本机，它已打开的页面也会立即断开。",
  "Remove {name}? It leaves mcp.servers in config.jsonc, and the MCP cell starts again without it.": "移除 {name}？它会从 config.jsonc 的 mcp.servers 中删去，MCP 细胞随后不带它重新启动。",
  "Replace": "替换",
  "Replace the {noun}": "替换 {noun}",
  "Request refused": "请求被拒绝",
  "Restart": "重启",
  "Restart and stop": "重启与停止",
  "Restart channels": "重启频道",
  "Restart it": "重启它",
  "Restart now": "立即重启",
  "Restart the organism": "重启实例",
  "Restart this organism? It starts again on config.jsonc as it is now; this page reconnects when it is back.": "重启此实例？它会按 config.jsonc 当前的内容重新启动；恢复后此页面会重新连接。",
  "Restart this organism? {what}. A turn that is running is picked up again after.": "重启此实例？{what}。正在运行的轮次会在重启后继续。",
  "Restarting. This page reconnects when the gateway is back.": "正在重启。网关恢复后，此页面会重新连接。",
  "Restarting: {text}": "正在重启：{text}",
  "Restarting…": "正在重启…",
  "Restore": "恢复",
  "Restored as the profile {profile}: {text}": "已恢复为配置档 {profile}：{text}",
  "Restores {n} file: {names}": "将恢复 {n} 个文件：{names}",
  "Restores {n} files: {names}": "将恢复 {n} 个文件：{names}",
  "Restoring as the profile {profile}: {step}… {seconds} s": "正在恢复为配置档 {profile}：{step}… {seconds} s",
  "Resume": "继续",
  "Retried": "已重试",
  "Retry": "重试",
  "Reusing the prompt from cache saved about {cost}.": "从缓存复用提示词节省了约 {cost}。",
  "Revert": "还原",
  "Rewind": "回退",
  "Rewind to before turn {n}?": "回退到第 {n} 轮之前？",
  "Right now": "当前",
  "Run": "运行",
  "Run now": "立即运行",
  "Runs as a systemd user unit, which starts it at login and after a crash.": "以 systemd 用户单元运行，登录时和崩溃后都会自动启动。",
  "Runs headless in the foreground (nodecode serve): nothing starts it again if it stops.": "在前台无界面运行（nodecode serve）：停止后没有任何东西会再启动它。",
  "Runs inside a shell, in that shell's terminal.": "在一个终端里运行，占用那个终端。",
  "SOUL.md as written above": "上面填写的 SOUL.md",
  "SOUL.md is the channel kit's: a channel (Discord, Telegram, Slack) gives its text to every conversation it holds as the agent's voice, from the next message on, unless its section in config.jsonc names a soul_file of its own. A shell and this page's sessions do not read it. Saved empty, the file is taken out.": "SOUL.md 属于频道套件：频道（Discord、Telegram、Slack）会把它的内容作为智能体的语气，用在它承载的每段对话中，从下一条消息起生效，除非该频道在 config.jsonc 中的配置另行指定了 soul_file。终端和本页面的会话不读取它。保存为空时，文件会被删除。",
  "SOUL.md of {name}": "{name} 的 SOUL.md",
  "Same as before": "与上次相同",
  "Sat": "周六",
  "Save": "保存",
  "Save key": "保存密钥",
  "Save the file": "保存文件",
  "Save the ticked sessions, and every session under them, to one file": "把勾选的会话及其下的所有会话保存到一个文件",
  "Save this session as Markdown": "把此会话保存为 Markdown",
  "Saved by the cache": "缓存节省",
  "Saved to {file}, as /connect saves it, once the provider has not refused the key. A key set in config.jsonc wins over one saved here. This page is never sent a key: only its last four characters.": "提供商没有拒绝这个密钥后，它会像 /connect 那样保存到 {file}。config.jsonc 中设置的密钥优先于这里保存的。此页面从不接收密钥本身，只接收它的最后四个字符。",
  "Saved {file}": "已保存 {file}",
  "Saved {name}": "已保存 {name}",
  "Saving…": "正在保存…",
  "Scheduled jobs": "定时任务",
  "Sections": "分区",
  "Select": "选择",
  "Send": "发送",
  "Sent": "发送",
  "Session": "会话",
  "Sessions": "会话",
  "Set up": "设置",
  "Set up walks a channel from its bot's token to who may talk to it. Check asks the platform what this channel's token can see. Restart channels starts every channel again on config.jsonc as it is now: what a changed section needs.": "「设置」带你为频道从机器人令牌一路配置到谁可以和它对话。「检查」会向平台询问此频道的令牌能看到什么。「重启频道」按 config.jsonc 当前的内容重新启动每个频道：改动某个配置段后需要这样做。",
  "Set up {name}": "设置 {name}",
  "Settings": "设置",
  "Share of spend": "花费占比",
  "Shell or web": "终端或网页",
  "Show all": "显示全部",
  "Show less": "收起",
  "Show the whole turn (0)": "显示整轮（0）",
  "Since {date} · API-equivalent prices": "自 {date}起 · 按 API 等价价格计",
  "Size": "大小",
  "Slow start": "起步慢",
  "Slow to start": "起步慢",
  "Slowest steps": "最慢的步骤",
  "Some calls have no price, so the cost is a floor.": "部分调用没有价格，所以费用是下限。",
  "Speed": "速度",
  "Spend": "花费",
  "Spend by day": "每日花费",
  "Start from": "起始内容",
  "Start it": "启动",
  "Started": "启动时间",
  "Starting…": "启动中…",
  "Status": "状态",
  "Stays on: {why}.": "保持开启：{why}。",
  "Steps": "步骤",
  "Steps it asked for": "它请求的步骤",
  "Stop": "停止",
  "Stop (Esc)": "停止（Esc）",
  "Stop the running turn": "停止正在运行的轮次",
  "Stop this organism? {what}. This page and every attached shell lose it until it is back.": "停止此实例？{what}。在它恢复之前，此页面和每个已连接的终端 都会与它断开。",
  "Stop {command}": "停止 {command}",
  "Stopped": "已停止",
  "Stopped. This page reconnects once it runs again.": "已停止。它再次运行后，此页面会重新连接。",
  "Stopping: {text}": "正在停止：{text}",
  "Store": "存储",
  "Summarize what changed in this folder since yesterday": "总结这个文件夹从昨天到现在的变化",
  "Summary": "摘要",
  "Sun": "周日",
  "Switched model": "换了模型",
  "System": "跟随系统",
  "Take back": "撤回",
  "Team seats": "团队席位",
  "Test": "测试",
  "Testing…": "正在测试…",
  "That image would make the prompt too large to send": "加上这张图片，提示词会大到无法发送",
  "The Dashboard has no range {range}, so it shows {shown}.": "仪表盘没有 {range} 这个范围，所以显示「{shown}」。",
  "The MCP cell is not loaded in this organism, so no server runs.": "此实例未加载 MCP 细胞，因此没有服务器运行。",
  "The cell folder is off in this process.": "此进程未启用细胞文件夹。",
  "The address as a QR code": "地址的二维码",
  "The agent took no steps in this range.": "此范围内代理没有执行任何步骤。",
  "The agent took {steps} over {time}.": "代理在 {time}内执行了 {steps}。",
  "The agent took {steps}.": "代理执行了 {steps}。",
  "The agent took {steps} in under a second.": "代理在不到一秒内执行了 {steps}。",
  "The backup failed: {error}": "备份失败：{error}",
  "The backup is deleted.": "备份已删除。",
  "The catalog could not be read: {error}": "无法读取目录：{error}",
  "The channels start again on what is saved:": "频道会按已保存的内容重新启动：",
  "The conversation moved; the files did not: {why}": "对话已移动，文件没有跟着恢复：{why}",
  "The default home.": "默认主目录。",
  "The default model is {model} on {provider}.": "默认模型已改为 {provider} 上的 {model}。",
  "The definition whole, as its file holds it: a save evaluates it and keeps it, one commit, as the agent's own eval would. The name stays its own; a new name is a new definition.": "完整的定义，即其文件中的内容：保存会对它求值并保存，一次提交，与智能体自己的 eval 相同。名称保持不变；新名称就是新的定义。",
  "The environment variable {name}": "环境变量 {name}",
  "The file itself, for the engineer: comments and all. Each secret reads [set], and saving puts it back from the file. A document that does not read, or that a setting above would refuse, is not saved, and why is said here.": "文件原文，给工程师用：连同注释。每个机密都显示为 [set]，保存时会从文件中放回原值。无法解析的文档，或上方某项设置会拒绝的文档，都不会保存，原因会显示在这里。",
  "The files in this session's folder": "此会话文件夹中的文件",
  "The first message opens the session": "发送第一条消息即开启会话",
  "The first word came after {wait}.": "首字在 {wait} 后到达。",
  "The first word took {wait}, about {times} times this session's usual {usual}.": "首字用了 {wait}，约为此会话常见值 {usual} 的 {times} 倍。",
  "The gateway refused the command: {why}": "网关拒绝了该命令：{why}",
  "The gateway refused what this tab sent: {why}": "网关拒绝了此标签页发送的内容：{why}",
  "The gateway refused {command}: {why}": "网关拒绝了 {command}：{why}",
  "The gateway this tab is attached to": "此标签页连接的网关",
  "The gateway this tab is attached to, v{version}": "此标签页连接的网关，v{version}",
  "The gateway, its log, keys and cells, channels and scheduled jobs": "网关、日志、密钥和细胞、频道以及定时任务",
  "The hub could not be read: {error}": "无法读取细胞中心：{error}",
  "The hub offers nothing for this platform yet.": "细胞中心暂时没有适用于此平台的细胞。",
  "The hub's index: {url}": "细胞中心索引：{url}",
  "The key for {provider} is removed.": "{provider} 的密钥已移除。",
  "The key for {provider} is saved, not checked: {why}": "{provider} 的密钥已保存，但未经检验：{why}",
  "The key for {provider} is saved.": "{provider} 的密钥已保存。",
  "The last try: {why}.": "上次尝试：{why}。",
  "The link": "远程访问",
  "The longest step took {time}.": "最长的步骤用了 {time}。",
  "The longest step took {time}: {title}.": "最长的步骤用了 {time}：{title}。",
  "The model took {model}% of the time and steps took {steps}%.": "模型占用了 {model}% 的时间，步骤占 {steps}%。",
  "The new session": "新会话",
  "The page is served by your own gateway and speaks only to it. The link the command prints carries the operator token after the": "此页面由你自己的网关提供，也只与它通信。命令打印的链接把操作令牌放在",
  "The profile a bare nodecode runs: {command}": "直接运行 nodecode 时使用的配置档：{command}",
  "The prompt changed at message {message}, so {tokens} tokens were read without the cache.": "提示词在第 {message} 条消息处发生了变化，所以有 {tokens} Token 没有经过缓存读取。",
  "The provider failed once ({status}); nodecode tried again.": "提供商出错 1 次（{status}），nodecode 已重试。",
  "The provider failed once; nodecode tried again.": "提供商出错 1 次，nodecode 已重试。",
  "The provider failed {n} time; nodecode tried again.": "提供商出错 {n} 次，nodecode 已重试。",
  "The provider failed {n} times ({status}); nodecode tried again.": "提供商出错 {n} 次（{status}），nodecode 已重试。",
  "The provider failed {n} times; nodecode tried again.": "提供商出错 {n} 次，nodecode 已重试。",
  "The relay names this machine's address once it answers.": "中继响应后，会为本机分配地址。",
  "The relay names this machine's address the first time the link is on.": "首次开启远程访问时，中继会为本机分配地址。",
  "The restore failed: {error}": "恢复失败：{error}",
  "The session will work in {folder}": "会话将在 {folder} 中工作",
  "The session's folder": "会话的文件夹",
  "The source that began each session: a shell or this page, a channel, a scheduled job": "每个会话由哪个来源发起：终端或本页面、频道、定时任务",
  "The turn stopped.": "本轮已中止。",
  "The turn stopped: {detail}": "本轮已中止：{detail}",
  "The {name} header": "请求头 {name}",
  "The {name} header, sent as {prefix}…": "请求头 {name}，以 {prefix}… 的形式发送",
  "The {n} call with a price cost {cost}.": "有价格的 {n} 次调用花费 {cost}。",
  "The {n} calls with a price cost {cost}.": "有价格的 {n} 次调用花费 {cost}。",
  "The {what} cell is not loaded in this organism, so there is nothing to show here.": "{what} 细胞没有加载到此实例中，所以这里没有可显示的内容。",
  "Theme": "主题",
  "There is no session {id} in this home, so this is a new one.": "此主目录中没有会话 {id}，所以这里是一个新会话。",
  "These 30 days": "近 30 天",
  "Thinking": "推理",
  "Thinking…": "思考中…",
  "This build names no hub.": "此构建没有指定细胞中心。",
  "This call as the gateway's timeline read it from the stored facts (turn.usage, turn.provider_request).": "这是网关时间线从存储的事实（turn.usage, turn.provider_request）中读出的这次调用。",
  "This call cost {cost} at the model's catalog price when it ran.": "按运行时的模型目录价格，这次调用花费 {cost}。",
  "This call cost {cost}.": "这次调用花费 {cost}。",
  "This call's request was not kept: it ran before nodecode kept requests, or while request_bodies.keep_mb was 0, or it was among the oldest dropped past that cap.": "这次调用的请求没有保留：它运行于 nodecode 开始保留请求之前，或运行时 request_bodies.keep_mb 为 0，或它属于超出上限后被丢弃的最早那批。",
  "This cannot be undone. Export first to keep a copy.": "此操作无法撤销。如需保留副本，请先导出。",
  "This file is empty.": "此文件为空。",
  "This gateway runs {home}, a home NODECODE_HOME names, which is not among the profiles.": "这个网关运行的是 {home}，一个由 NODECODE_HOME 指定、不在配置档之列的主目录。",
  "This is the index as last read; reading it now failed: {error}": "这是上次读到的索引；这次读取失败：{error}",
  "This machine's page answers at its address, for every browser you allowed.": "本机页面在该地址上响应，你允许的每个浏览器都能访问。",
  "This machine's page, from anywhere": "随时随地访问本机页面",
  "This session": "此会话",
  "This session has no folder to show.": "这个会话没有可显示的文件夹。",
  "This session has no turn {n}, so turn {last} is open.": "此会话没有第 {n} 轮，所以打开了第 {last} 轮。",
  "This session has no turn {n}.": "此会话没有第 {n} 轮。",
  "This tab needs its link.": "此标签页需要它的链接。",
  "This week": "近 7 天",
  "Thu": "周四",
  "Tick every session shown": "勾选所有显示的会话",
  "Tick sessions to export or delete them": "勾选会话以导出或删除",
  "Time": "用时",
  "Timed out": "超时",
  "Times": "次数",
  "Today": "今天",
  "Tokens": "Token",
  "Tools from servers that speak the Model Context Protocol (MCP), each set under mcp.servers in config.jsonc; the agent calls them from its eval tool. Test lists what a server offers on the connection the agent uses, and reconnects one that is down. Adding or removing a server starts the MCP cell again, which reconnects every server.": "来自支持 Model Context Protocol（MCP）的服务器的工具，每个都配置在 config.jsonc 的 mcp.servers 下；智能体通过它的 eval 工具调用它们。「测试」在智能体所用的连接上列出服务器提供的内容，并重连已断开的服务器。添加或移除服务器会重启 MCP 细胞，所有服务器都会重新连接。",
  "Tools: {names}": "工具：{names}",
  "Totals": "合计",
  "Transcript": "对话记录",
  "Tries": "尝试次数",
  "Try now": "立即重试",
  "Trying…": "正在重试…",
  "Tue": "周二",
  "Turn off": "关闭",
  "Turn on": "开启",
  "Turn on MCP under Cells to give the agent tools from MCP servers.": "在「细胞」中开启 MCP，即可让智能体使用 MCP 服务器提供的工具。",
  "Turn on {folder} under Cells, then give it a {section} section in config.jsonc.": "在「细胞」下开启 {folder}，再在 config.jsonc 中为它添加 {section} 配置段。",
  "Turn on {folder} under Cells.": "在「细胞」下开启 {folder}。",
  "Turn the link off? Every browser you allowed is cut off until it is on again; the list of them is kept.": "关闭远程访问？你允许的所有浏览器都会断开，直到重新开启；已允许的列表会保留。",
  "Turn the link off? This page came through it, so it is cut off now; turning it on again takes a browser on this machine, or /link on in a shell.": "关闭远程访问？本页面正是经由它打开的，会立即断开；要重新开启，需要在本机的浏览器中操作，或在终端中运行 /link on。",
  "Turn {name} off": "关闭 {name}",
  "Turn {name} off? Its folder leaves {folder} and it stops now; its code stays loaded in this organism until a restart.": "关闭 {name}？它的文件夹会移出 {folder}，它也会立即停止；它的代码在重启之前仍加载在此实例中。",
  "Turn {name} on": "开启 {name}",
  "Turn {n} made no model call {call}.": "第 {n} 轮没有第 {call} 次模型调用。",
  "Type (optional)": "类型（可选）",
  "What the agent keeps and does not run — memories, skills in prose — and the definitions of its own layer, ranked by use: the index at the head of every conversation lists the hot ones, and the agent reads one before it follows it. A memory never cools; a skill or a definition unused for a while does. A new session lists a change at once, one already running after its next eviction, or at once after /index reload in it.": "智能体保存而不运行的内容——记忆、以文字写成的技能——以及它自己层中的定义，按使用情况排序：每段对话开头的索引列出常驻的那些，智能体在遵循某一项之前会先读它。记忆永远不会变冷；技能或定义一段时间不用就会变冷。新会话会立即列出改动，已在运行的会话在下次上下文驱逐后列出，或在其中运行 /index reload 后立即列出。",
  "Why, and how to apply it (optional)": "原因，以及如何应用（可选）",
  "definition": "定义",
  "skill": "技能",
  "the default": "默认模型",
  "used {when}": "使用于 {when}",
  "{hot} hot · {cold} cold · {cells} cells": "{hot} 条常驻 · {cold} 条冷存 · {cells} 个细胞",
  "{name} refused to start: {why}": "{name} 启动被拒绝：{why}",
  "Use this folder": "使用此文件夹",
  "where the gateway runs": "网关运行的位置",
  "{name}'s definition": "{name} 的定义",
  "{n} of {m} · {folder}": "{m} 个中的 {n} 个 · {folder}",
  "{turn} over time: plus and minus zoom, 0 shows all of it, the arrows move along it": "{turn}的时间线：加号和减号缩放，0 显示全部，方向键沿时间移动",
  "{turn} · model call {n} of {calls}": "{turn} · 第 {n} 次模型调用（共 {calls} 次）",
  "Turned off in config.jsonc (enabled: false)": "已在 config.jsonc 中关闭（enabled: false）",
  "Turns": "轮次",
  "Turns by weekday and hour, {n} in all": "按星期和小时统计的轮次，共 {n} 轮",
  "Type ids": "输入 id",
  "Unpair": "解除配对",
  "Unpair {name}? They can no longer talk to the {platform} bot; writing to it again gives them a new code to ask with.": "解除与 {name} 的配对？对方将无法再与 {platform} 机器人对话；再给它发消息会拿到新的配对码来请求。",
  "Update": "更新",
  "Update now": "立即更新",
  "Updating…": "更新中…",
  "Upload": "上传",
  "Uploaded {name}": "已上传 {name}",
  "Uploaded {name} to {dir}": "已上传 {name} 到 {dir}",
  "Uploading {name} · {share}% of {size}": "正在上传 {name} · 已完成 {share}%，共 {size}",
  "Used from its next read; nothing restarts.": "下次读取时生效，无需重启。",
  "Version": "版本",
  "View": "视图",
  "View this image": "查看这张图片",
  "View {name}": "查看 {name}",
  "Waited {wait} for the first word. This session usually waits {usual}.": "等了 {wait} 才出首字。此会话通常只等 {usual}。",
  "Waiting for the first word": "等待首字",
  "Warnings": "警告",
  "Wed": "周三",
  "Well-known servers, each checked against its own project's documentation. Add fills the form above with how it runs and asks only for the keys it needs; a server is someone else's code, so read its page first.": "常用服务器，每个都已对照其项目文档核对过。「添加」会把运行方式填进上方表单，只询问它需要的密钥；服务器是别人写的代码，请先阅读它的主页。",
  "Went wrong": "出错",
  "What it sent: {n} tokens": "发送内容：{n} Token",
  "What it wrote to its stderr": "它写到 stderr 的内容",
  "What it wrote: {n} tokens": "输出内容：{n} Token",
  "What should nodecode do?": "要让 nodecode 做什么？",
  "What the agent did": "代理做了什么",
  "What this profile is for": "这个配置档的用途",
  "What to do": "要做什么",
  "What was sent": "发送内容",
  "What went wrong": "出了什么问题",
  "When": "时间",
  "When reads as 30m, every 2h, in 45m, at 17:30, every day at 9am, weekdays at 9:30, every mon,wed at 18:00, five-field cron (0 9 * * 1-5), or a time (2026-10-01T09:00); local time.": "「时间」可以写成 30m、every 2h、in 45m、at 17:30、every day at 9am、weekdays at 9:30、every mon,wed at 18:00、五段式 cron（0 9 * * 1-5），或一个时刻（2026-10-01T09:00）；均按本地时间。",
  "When turns ran": "轮次运行时段",
  "Where in the folder": "在文件夹中的位置",
  "Where keys are made: {pages}": "在这里创建密钥：{pages}",
  "Where the model calls went": "模型调用花在了哪里",
  "Where the money went": "钱花在了哪里",
  "Where the time and money went": "时间和花费去了哪里",
  "Which source": "哪个来源",
  "Work": "工作",
  "Worked": "工作记录",
  "Working": "工作中",
  "Worth a look": "值得一看",
  "Writing": "输出用时",
  "Writing speed": "输出速度",
  "Writing the prompt to cache cost about {cost} more than reading it back saved.": "把提示词写入缓存的花费，比读回时节省的多了约 {cost}。",
  "Writing the reply": "撰写回复",
  "Written": "输出量",
  "Written to cache": "写入缓存",
  "Your own folder.": "你自己的文件夹。",
  "Zoom in (+)": "放大（+）",
  "Zoom out (−)": "缩小（−）",
  "a call in another session, {session}": "另一个会话中的调用，{session}",
  "a channel (discord, telegram) with the channel kit": "discord 或 telegram 频道及频道套件",
  "a fork of {from}, its memory, skills and keys copied": "{from} 的分叉，复制其记忆、技能和密钥",
  "a fork of {source}": "{source} 的分叉",
  "a new one replaces the one kept": "新的会替换已保存的",
  "a shell": "一个终端",
  "a-z, 0-9, . _ and -, starting with a letter or digit": "a-z、0-9、. _ 和 -，以字母或数字开头",
  "a-z, 0-9, _ and -, starting with a letter or digit": "a-z、0-9、_ 和 -，以字母或数字开头",
  "cells": "细胞",
  "all of it": "全部",
  "allowed {when}": "允许于 {when}",
  "an empty home": "一个空的主目录",
  "asks for {keys}": "需要填写 {keys}",
  "boots by default": "默认启动",
  "brings {cells}": "会一并带上 {cells}",
  "cache hit": "缓存命中率",
  "cache hit rate": "缓存命中率",
  "cached {cached} of {prompt}": "缓存 {cached} / {prompt}",
  "checked {when}, in {seconds} s": "检查于 {when}，用时 {seconds} s",
  "config": "配置",
  "config.jsonc does not read: {error}. Fix it in the editor below.": "config.jsonc 无法解析：{error}。请在下方编辑器中修复。",
  "config.jsonc without its channels, SOUL.md, themes and the installed cells are copied; memory, skills, secrets and auth.json are shared by link, so a correction lives in one place. A fresh store and a fresh layer.": "复制 config.jsonc（不含频道）、SOUL.md、主题和已安装的细胞；记忆、技能、机密信息和 auth.json 通过链接共享，改一处即处处生效。存储和代码层都是全新的。",
  "connected": "已连接",
  "connecting": "连接中",
  "context tokens": "上下文 Token",
  "context {used} / {window}": "上下文 {used} / {window}",
  "cost per tool": "各工具费用",
  "cost_usd · no price known": "cost_usd · 价格未知",
  "cost_usd · partly priced": "cost_usd · 部分有价格",
  "default: {value}": "默认：{value}",
  "defaults": "默认值",
  "degraded": "降级",
  "done": "完成",
  "error rate": "错误率",
  "every session": "所有会话",
  "exit {code}": "退出码 {code}",
  "failed": "失败",
  "family {family}": "类别 {family}",
  "family {family} · {n} model calls' worth": "类别 {family} · 相当于 {n} 次模型调用",
  "folder": "文件夹",
  "fork: {name}": "分叉：{name}",
  "from the environment": "来自环境变量",
  "from the hub, {pin}": "来自细胞中心，{pin}",
  "from {source}": "来自 {source}",
  "has a SOUL.md": "有 SOUL.md",
  "here": "当前",
  "ids, separated by spaces or commas": "id，用空格或逗号分隔",
  "image": "图片",
  "input + cached + cache write": "输入 + 缓存 + 缓存写入",
  "input {input} · cached {cached} · output {output}": "输入 {input} · 缓存 {cached} · 输出 {output}",
  "its page": "项目主页",
  "just now": "刚刚",
  "kept from the config": "沿用配置中的值",
  "keys": "密钥",
  "last message {when}": "最后消息 {when}",
  "link": "链接",
  "link, leads nowhere": "链接，指向不存在的位置",
  "link, leads outside the folder": "链接，指向文件夹之外",
  "mcp.enabled is false in config.jsonc: no server starts until it is true.": "config.jsonc 中 mcp.enabled 为 false：改为 true 之前不会启动任何服务器。",
  "memory": "记忆",
  "missing": "缺失",
  "model calls per tool": "各工具模型调用",
  "model calls that asked for no step": "未请求任何步骤的模型调用",
  "needs setting up": "待设置",
  "needs {needs}": "需要 {needs}",
  "never used": "从未使用",
  "next try in {n} s": "{n} 秒后重试",
  "next {when}": "下次 {when}",
  "no SOUL.md": "没有 SOUL.md",
  "no key": "无需密钥",
  "no longer on disk": "已不在磁盘上",
  "no message array": "无消息数组",
  "no message yet": "还没有消息",
  "no price known": "价格未知",
  "no run left": "不再运行",
  "no status": "无状态码",
  "no store yet": "尚无存储",
  "nodecode {version}, {uptime}.": "nodecode {version}，{uptime}。",
  "nodecode {version}.": "nodecode {version}。",
  "nodecode, a new session": "nodecode，新会话",
  "none": "无",
  "none ticked": "未勾选",
  "not connected": "未连接",
  "not installed: add nodecode-channel-{id} from the Cells tab, then set it up here": "未安装：先在「细胞」标签页添加 nodecode-channel-{id}，再回到这里设置",
  "not open": "未打开",
  "not running": "未运行",
  "not set": "未设置",
  "not set up": "未设置",
  "not started": "未启动",
  "nothing: this one was kept whole": "无：这次是完整保存的",
  "now": "刚刚",
  "npx, or https://host/mcp": "npx，或 https://host/mcp",
  "off": "已关闭",
  "on": "已开启",
  "open this home's organism in a browser tab": "在浏览器标签页中打开此主目录的实例",
  "output tokens / stream time": "输出 Token / 输出时长",
  "paste it here": "粘贴到这里",
  "paused": "已暂停",
  "provider requests": "提供商请求",
  "raw request body": "原始请求体",
  "raw request body · application/json": "原始请求体 · application/json",
  "read the code": "阅读代码",
  "reads' discount less writes' premium": "读取折扣减去写入溢价",
  "reconnecting": "重新连接中",
  "recorded": "已记录",
  "recorded · {by}": "已记录 · {by}",
  "refused": "被拒绝",
  "refused at start": "启动时被拒绝",
  "restore failed": "恢复失败",
  "running": "运行中",
  "saved here": "保存在此",
  "secrets": "机密",
  "serving, pid {pid}": "运行中，pid {pid}",
  "serving, pid {pid} on port {port}": "运行中，pid {pid}，端口 {port}",
  "set": "已设置",
  "set in config.jsonc": "在 config.jsonc 中设置",
  "set; type a new one to replace it": "已设置；输入新的即可替换",
  "shares {names}": "共享 {names}",
  "signed in": "已登录",
  "skills": "技能",
  "starting": "启动中",
  "status {status}": "状态 {status}",
  "stopped": "已停止",
  "stopping": "正在停止",
  "store {size}": "存储 {size}",
  "sum cost_usd": "cost_usd 合计",
  "sum cost_usd · {n} unpriced": "cost_usd 合计 · {n} 次无价格",
  "systemd's journal, {where}": "systemd 日志（journal），{where}",
  "the call before it in this turn": "本轮中的上一次调用",
  "the first {size} ({share})": "前 {size}（{share}）",
  "the gateway isn't answering": "网关没有响应",
  "the last call of an earlier turn": "之前某轮的最后一次调用",
  "the same, for another profile's home": "同上，用于另一个配置档的主目录",
  "the session store, with its log": "会话存储及其日志",
  "the settings of {from}, its memory, skills and keys shared by link": "{from} 的设置，通过链接共享其记忆、技能和密钥",
  "the settings of {source}": "{source} 的设置",
  "the start": "开头",
  "the variable's name": "变量名",
  "themes": "主题",
  "this browser": "此浏览器",
  "this organism": "此实例",
  "this page": "本页面",
  "time · cost": "用时 · 费用",
  "tool": "工具",
  "tool calls": "工具调用",
  "trying now": "正在重试",
  "turn {n}": "第 {n} 轮",
  "turn {n} · steer": "第 {n} 轮 · 插话",
  "turn.started by local hour": "turn.started，按本地时间的小时",
  "turn.usage voided: attempts that failed after they began to stream": "turn.usage voided：开始流式输出后失败的尝试",
  "untitled": "未命名",
  "up {h}h {m}m": "已运行 {h}h {m}m",
  "up {m}m": "已运行 {m}m",
  "up {n} days": "已运行 {n} 天",
  "wall time": "墙钟时间",
  "wall {time}": "墙钟 {time}",
  "whole turn, {time}": "整轮，{time}",
  "{cell} reads this when it starts.": "{cell} 在启动时读取此配置段。",
  "{agent} asks to open this machine. Allow it only if its page shows this same code.": "{agent} 请求访问本机。只有它的页面显示同样的代码时才允许。",
  "{agent} in {place} asks to open this machine. Allow it only if its page shows this same code.": "位于 {place} 的 {agent} 请求访问本机。只有它的页面显示同样的代码时才允许。",
  "{asking} asking · {paired} let in": "{asking} 个请求 · 已放行 {paired} 人",
  "{ask} (optional)": "{ask}（可选）",
  "{calls} and {steps}.": "{calls}和 {steps}。",
  "{cost} over {calls}, each call's cost split evenly over the steps it asked for; a call that asked for none was writing the reply.": "{calls}共花费 {cost}，每次调用的费用平均分摊到它请求的步骤上；没有请求步骤的调用是在撰写回复。",
  "{failed} of {attempts} went wrong": "{attempts}中有 {failed} 次出错",
  "{failed} of {attempts} went wrong: {statuses}": "{attempts}中有 {failed} 次出错：{statuses}",
  "{failed} of {turns} failed": "{turns}中有 {failed} 轮失败",
  "{field} takes a whole number": "{field} 需要整数",
  "{folder} holds no cell.": "{folder} 中没有细胞。",
  "{fresh} of {prompt} tokens were read without the cache.": "{prompt} Token 中有 {fresh} 没有经过缓存读取。",
  "{from} to {to} of {whole}": "{from} 至 {to}，共 {whole}",
  "{from}'s SOUL.md if it has one": "{from} 的 SOUL.md（如果有）",
  "{host} refused this tab's token": "{host} 拒绝了此标签页的令牌",
  "{hours} {n} min": "{hours} {n} 分钟",
  "{id} · open its session, {session}": "{id} · 打开它的会话 {session}",
  "{kept} of {total} lines": "{kept} / {total} 行",
  "{model}, {effort} effort": "{model}，推理强度 {effort}",
  "{name} (this page)": "{name}（本页面）",
  "{name} is already in {folder}. Replace it with the one you chose?": "{folder} 中已有 {name}。用你选择的文件替换它吗？",
  "{name} is not a profile name: a-z, 0-9, _ and -, 64 at most, starting with a letter or digit.": "{name} 不是有效的配置档名称：只能用 a-z、0-9、_ 和 -，最多 64 个字符，以字母或数字开头。",
  "{name} started again.": "{name} 已重新启动。",
  "{name} stays: {why}": "{name} 保留：{why}",
  "{name}, whole": "查看完整的 {name}",
  "{n} allowed": "已允许 {n} 个",
  "{n} attempt": "{n} 次尝试",
  "{n} attempts": "{n} 次尝试",
  "{n} call": "{n} 次调用",
  "{n} call has no price and is left out.": "{n} 次调用没有价格，未计入。",
  "{n} call has no price, so the spend is a floor.": "{n} 次调用没有价格，所以花费是下限。",
  "{n} call has no price.": "{n} 次调用没有价格。",
  "{n} calls": "{n} 次调用",
  "{n} calls have no price and are left out.": "{n} 次调用没有价格，未计入。",
  "{n} calls have no price, so the spend is a floor.": "{n} 次调用没有价格，所以花费是下限。",
  "{n} calls have no price.": "{n} 次调用没有价格。",
  "{n} change waits for a restart.": "{n} 项改动等待重启。",
  "{n} changes wait for a restart.": "{n} 项改动等待重启。",
  "{n} characters, fold": "{n} 个字符，折叠",
  "{n} days": "{n} 天",
  "{n} delivered": "已投递 {n} 条",
  "{n} exec running": "{n} 个后台进程运行中",
  "{n} execs running": "{n} 个后台进程运行中",
  "{n} failed": "失败 {n}",
  "{n} failed · turn.failed": "失败 {n} · turn.failed",
  "{n} file was changed outside the session and left as it is": "{n} 个文件在会话外被改动过，已保持原样",
  "{n} files were changed outside the session and left as they are": "{n} 个文件在会话外被改动过，已保持原样",
  "{n} flag": "{n} 个标记",
  "{n} flags": "{n} 个标记",
  "{n} h ago": "{n} 小时前",
  "{n} hour": "{n} 小时",
  "{n} hours": "{n} 小时",
  "{n} item": "{n} 项",
  "{n} items": "{n} 项",
  "{n} key": "{n} 个键",
  "{n} keys": "{n} 个键",
  "{n} line": "{n} 行",
  "{n} lines": "{n} 行",
  "{n} min ago": "{n} 分钟前",
  "{n} minute": "{n} 分钟",
  "{n} minutes": "{n} 分钟",
  "{n} model call": "{n} 次模型调用",
  "{n} model calls": "{n} 次模型调用",
  "{n} more": "还有 {n} 条",
  "{n} more setting": "另外 {n} 项设置",
  "{n} more settings": "另外 {n} 项设置",
  "{n} more stay.": "另有 {n} 个会话保留。",
  "{n} more stays.": "另有 {n} 个会话保留。",
  "{n} more waiting": "还有 {n} 个等待中",
  "{n} node": "{n} 个节点",
  "{n} nodes": "{n} 个节点",
  "{n} of these {calls} have no price, so they are counted instead, each split evenly over the steps it asked for; a call that asked for none was writing the reply.": "这 {calls}中有 {n} 次没有价格，所以改为计数：每次调用平均分摊到它请求的步骤上；没有请求步骤的调用是在撰写回复。",
  "{n} of those tokens": "其中 {n} Token",
  "{n} on": "已开启 {n} 个",
  "{n} profile": "{n} 个配置档",
  "{n} profiles": "{n} 个配置档",
  "{n} s left": "剩余 {n} 秒",
  "{n} second": "{n} 秒",
  "{n} seconds": "{n} 秒",
  "{n} session": "{n} 个会话",
  "{n} sessions": "{n} 个会话",
  "{n} step": "{n} 个步骤",
  "{n} step returned an error.": "{n} 个步骤返回了错误。",
  "{n} steps": "{n} 个步骤",
  "{n} steps returned an error.": "{n} 个步骤返回了错误。",
  "{n} thing to look at": "{n} 项需要查看",
  "{n} things are worth a look below.": "下面有 {n} 处值得一看。",
  "{n} things to look at": "{n} 项需要查看",
  "{n} ticked": "已勾选 {n} 个",
  "{n} tokens": "{n} Token",
  "{n} tokens ({share})": "{n} Token（{share}）",
  "{n} tokens, {share} of {window}": "{n} Token，占 {window} 的 {share}",
  "{n} tool": "{n} 个工具",
  "{n} tool call": "{n} 次工具调用",
  "{n} tool calls": "{n} 次工具调用",
  "{n} tools": "{n} 个工具",
  "{n} turn": "{n} 轮",
  "{n} turn failed of {total}.": "{total} 轮中有 {n} 轮失败。",
  "{n} turn failed.": "{n} 轮失败。",
  "{n} turn in all.": "共 {n} 轮。",
  "{n} turn was stopped.": "{n} 轮被停止。",
  "{n} turns": "{n} 轮",
  "{n} turns failed of {total}.": "{total} 轮中有 {n} 轮失败。",
  "{n} turns failed.": "{n} 轮失败。",
  "{n} turns in all.": "共 {n} 轮。",
  "{n} turns were stopped.": "{n} 轮被停止。",
  "{path}, message {n}": "{path}，第 {n} 条消息",
  "{path}, message {n} of {total}": "{path}，第 {n} 条消息（共 {total} 条）",
  "{pct}% context": "上下文 {pct}%",
  "{platform} gives no code: pairing is false in channels.{id}, so a stranger's direct message goes unanswered.": "{platform} 不发配对码：channels.{id} 中的 pairing 为 false，所以陌生人的私信不会得到回复。",
  "{platform} · asked {ago} · its code lapses in {n} min": "{platform} · {ago}提出请求 · 配对码 {n} 分钟后失效",
  "{platform} · let in {when}": "{platform} · 放行于 {when}",
  "{provider}/ — no listing ({why})": "{provider}/ — 无列表（{why}）",
  "{range}, {calls} across {sessions}.": "{range}，{sessions}共 {calls}。",
  "{range}, {cost} across {sessions}.": "{range}，{sessions}共花费 {cost}。",
  "{said}. A setting a cell reads applies when it starts again.": "{said}。细胞读取的设置会在它重新启动时生效。",
  "{share} failed · tool calls": "失败 {share} · 工具调用",
  "{share} from cache": "缓存命中 {share}",
  "{share} of the prompt came from cache.": "{share} 的提示词来自缓存。",
  "{size} · {n} bytes": "{size} · {n} 字节",
  "{source} only, in every folder.": "仅「{source}」，所有文件夹。",
  "{state}, {tools}": "{state}，{tools}",
  "{state}, {tools}, in {ms}": "{state}，{tools}，用时 {ms}",
  "{steps}, {time} of work.": "{steps}，共工作 {time}。",
  "{steps}.": "{steps}。",
  "{time}, {n} tokens": "{time}，{n} Token",
  "{time}, {n} tokens, {rate} a second": "{time}，{n} Token，每秒 {rate}",
  "{tool} {n} ({failed} failed)": "{tool} {n}（失败 {failed}）",
  "{turns} in {time}, about {cost}.": "{time}内 {turns}，约 {cost}。",
  "{turns} in {time}.": "{time}内 {turns}。",
  "{turns}, {failed} failed.": "{turns}，其中 {failed} 轮失败。",
  "{used} context": "上下文 {used}",
  "{used} in use. The turns stay in the transcript, dimmed; the model stops seeing them.": "已用 {used}。这些轮次仍留在对话记录中并变暗；模型不再看到它们。",
  "{used} of {window}": "已用 {used}，共 {window}",
  "{used} of {window} in use. The turns stay in the transcript, dimmed; the model stops seeing them.": "已用 {used}，共 {window}。这些轮次仍留在对话记录中并变暗；模型不再看到它们。",
  "{used} of {window} on {model}": "{model} 上已用 {used}，共 {window}",
  "— queued": "— 排队中",
  "— steer": "— 插话",
  "• context evicted above": "• 以上内容已移出上下文",
  "‹ Model": "‹ 模型",
  "‹ Reasoning": "‹ 推理",
  "binary": "二进制",
  "{n} more file": "另有 {n} 个文件",
  "{n} more files": "另有 {n} 个文件",
  "Reflection recap": "反思小结",
  "More": "更多",
  "Send this prompt again": "再发送一次这条消息",
  "Attach files": "添加文件",
  "Attach files: an image rides the message, any other file goes into the session's folder": "添加文件：图片随消息一起发送，其他文件放入会话的文件夹",
  "Attached: {path}": "附件：{path}",
  "It goes into {path} when the message is sent": "发送消息时，它会放入 {path}",
  "{name} is already in {folder}: this one goes in as {as}": "{folder} 里已有 {name}：这个会以 {as} 放入",
  "{name} is taken in {folder}, so this one goes in as {as}: send again": "{folder} 里已有 {name}，所以这个会以 {as} 放入：请再发送一次",
  "{name} was refused: {why}. Remove it to send.": "{name} 被拒绝：{why}。移除它才能发送。",
  "Retry or remove {name} to send": "重试或移除 {name} 才能发送",
  "Stopped uploading {name}": "已停止上传 {name}",
  "{name} is already in {folder} and stays there": "{name} 已在 {folder} 中，会留在那里",
  "A picture sent with this prompt is no longer on disk: rewind the turn and attach it again": "随这条消息发送的一张图片已不在磁盘上：请回退这一轮，再添加一次",
  "The picture sent with turn {n} is no longer on disk: attach it again": "第 {n} 轮随消息发送的图片已不在磁盘上：请再添加一次",
  "{count} pictures sent with turn {n} are no longer on disk: attach them again": "第 {n} 轮随消息发送的 {count} 张图片已不在磁盘上：请再添加一次",
  "It goes into the session's folder when the first message opens the session": "第一条消息开启会话时，它会放入会话的文件夹",
  "Remove this file": "移除这个文件",
  "not attached": "未添加",
  "uploading {share}%": "正在上传 {share}%",
  "{name} is a folder: attach the files in it": "{name} 是文件夹：请添加其中的文件",
  "exited {code}": "退出码 {code}",
  "moved to the background": "已转入后台",
  "Its output is over the message box while it runs, and under the turn once it ends.": "运行时，它的输出在消息框上方；结束后，在这一轮的下方。",
  "Stopped by you after {time}": "你在 {time} 后停止了它",
  "Stopped by you": "你停止了它",
  "Stopped: the gateway shut down while this ran": "已停止：它运行时网关关闭了",
  "Stopped by the model after {time}": "模型在 {time} 后停止了它",
  "Stopped by the model": "模型停止了它",
  "Stopped: {reason}": "已停止：{reason}",
  "Earlier output is not kept": "更早的输出未保留",
  "no output yet": "尚无输出",
  "Running in the background": "后台运行中",
  "error: {report}": "错误：{report}",
  "background job {end}": "后台任务{end}",
  "Woke": "唤醒",
  "eval {id}": "求值 {id}",
  "Hide the sessions": "隐藏会话列表",
  "Show the sessions": "显示会话列表",
  "This folder only": "仅此文件夹",
  "This folder only: {n} of {m}": "仅此文件夹：{m} 个中的 {n} 个",
  "Markdown": "Markdown",
  "Jump to": "跳到",
  "What this is": "这是什么",
  "Manage": "管理",
  "Turning on…": "正在开启…",
  "The link cell is off. On, it gives this machine's page an address you can open from anywhere, a phone too.": "远程访问细胞没有开启。开启后，这台机器的页面会有一个在任何地方都能打开的地址，手机也可以。",
  "Scan the code with a phone; when it asks, allow it here.": "用手机扫描二维码；手机请求访问时，在这里允许它。",
  "{n} attempt cut off": "{n} 次尝试被截断",
  "{n} attempts cut off": "{n} 次尝试被截断",
  "Something new since you last looked": "上次查看后有新内容",
  "Back into the box, to edit or send again": "放回输入框，可修改后再发送",
  "Enter steers this turn · Tab queues for after it": "Enter 插话到这一轮 · Tab 排到这一轮之后",
  "Steer this turn (Enter): it ends at its next step and this runs next": "插话到这一轮（Enter）：它在下一步结束，接着运行这条",
  "Send (Enter)": "发送（Enter）",
  "Steer this turn": "插话到这一轮",
  "Queue for after this turn": "排到这一轮之后",
  "Queue for after this turn (Tab)": "排到这一轮之后（Tab）",
  "Keys in this box": "输入框的按键",
  "Send; while a turn runs, steer: this runs at its next step": "发送；轮次运行时则插话：在它的下一步运行这条",
  "While a turn runs, queue this for after it": "轮次运行时，把这条排到它之后",
  "A new line": "换行",
  "While a turn runs, take the last queued prompt back; else the prompt before": "轮次运行时，撤回最后一条排队的提示词；否则是上一条提示词",
  "The prompt after": "下一条提示词",
  "{n} with news in other folders": "其他文件夹中有 {n} 个会话有新内容"
};
